version: "3.9"
services:
  server:
    ports:
      - "8081:8081"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8081",
        "--reload",
      ]

  postgres:
    ports:
      - "5432:5432"

  nginx:
    ports:
      - "8080:80"
