version: "3.9"
services:
  server:
    image: tmhntr/health-backend:latest
    environment:
      - PORT=80
      - DATABASE_LOGIN_URL=postgresql://postgres:secret@db/postgres
      - ENVIRONMENT=production
    depends_on:
      - db
  client:
    image: tmhntr/health-frontend:latest
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data: