version: "3.9"

services:
  health-backend:
    image: tmhntr/health-backend:latest
    container_name: health-backend
    environment:
      - PORT=80
      - DATABASE_LOGIN_URL=postgresql://postgres:secret@db/postgres
      # - DEBUG=1
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  health-frontend:
    image: tmhntr/health-frontend:latest
    container_name: health-frontend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
      
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=3600

volumes:
  postgres-data: