version: "3.9"
services:
  server:
    ports:
      - "3001:80"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
      ]

  postgres:
    ports:
      - "5432:5432"

  nginx:
    ports:
      - "8080:80"

  client:
    ports:
      - "3000:80"
