version: "3.9"
services:
  server:
    build: ./server
    # ports:
    #   - "8081:8081"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    command: [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        # "--reload",
      ]

  client:
    build: ./client
    # ports:
    #   - "3000:80"

  postgres:
    image: "postgres:latest"
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  postgres:
